#!/usr/bin/env python

import sys
import os
import pyvctrl


def usage():
    print("""pyvctrl v1.0 Dirk Baechle, <dl9obn@darc.de>, 2022-01-05

Usage:

  pyvctrl [-l]

where options are:

  -l : Logging mode, simply output the current available parameters to stdout every 5s

""")


def main():
    # Process command line arguments
    if len(sys.argv) < 2:
        usage()
        sys.exit(0)

    LOGMODE = False

    for arg in sys.argv[1:]:
        if arg in ["-h","-?","--help"]:
            usage()
            sys.exit(0)

        if arg in ["-l","--logging","--logging-mode"]:
            LOGMODE = True

    if LOGMODE:
        pass
    else:
        pass


if __name__ == "__main__":
    main()
